default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: myrails_development
  username: tute
  password: ubemeiQuie7zie3nei8e
  host: localhost
  port: 5432

test:
  <<: *default
  database: myrails_test
  username: tute
  password: ubemeiQuie7zie3nei8e
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: myrails_production
    username: myrails
    password: <%= ENV["MYRAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: myrails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: myrails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: myrails_production_cable
    migrations_paths: db/cable_migrate
